<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.API\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\APIGateway.Application\APIGateway.Application.csproj" />
    <ProjectReference Include="..\APIGateway.Domain\APIGateway.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>

</Project>
