<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<AssemblyName>IdeaSpace.Modules.ClientNotification.API</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\ClientNotification.Application\ClientNotification.Application.csproj" />
    <ProjectReference Include="..\ClientNotification.Infrastructure\ClientNotification.Infrastructure.csproj" />
  </ItemGroup>

</Project>
